[profile.default]
# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
solc_version = '0.8.21'
auto_detect_solc = false
evm_version = 'london'
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./" }]
deny_warnings = false

remappings = [
    "@solmate/=lib/solmate/src/",
    "@forge-std/=lib/forge-std/src/",
    "@ds-test/=lib/forge-std/lib/ds-test/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@ccip=lib/ccip/",
    "@oapp-auth=lib/OAppAuth/src/",
]

[rpc_endpoints]
berachain = "${BERA_CHAIN_RPC_URL}"

[etherscan]
berachain = { key = "JRGY1ZKMXDN2W6QI48F3NWP3CNPKUTU2GU", chain = 80094, url = "https://api.routescan.io/v2/network/mainnet/evm/80094/etherscan" }


[fmt]
FOUNDRY_FMT_LINE_LENGTH = 120
FOUNDRY_FMT_TAB_WIDTH = 4
FOUNDRY_FMT_BRACKET_SPACING = true
FOUNDRY_FMT_INT_TYPES = "long"
FOUNDRY_FMT_MULTILINE_FUNC_HEADER = "attributes_first"
FOUNDRY_FMT_QUOTE_STYLE = "double"
FOUNDRY_FMT_NUMBER_UNDERSCORE = "thousands"
FOUNDRY_FMT_OVERRIDE_SPACING = true
FOUNDRY_FMT_WRAP_COMMENTS = false
FOUNDRY_FMT_IGNORE = []
