[profile.default]
# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
solc_version = '0.8.21'
auto_detect_solc = false
evm_version = 'london'
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./" }]
deny_warnings = false
remappings = [
    "@solmate/=lib/solmate/src/",
    "@forge-std/=lib/forge-std/src/",
    "@ds-test/=lib/forge-std/lib/ds-test/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@ccip=lib/ccip/",
    "@oapp-auth=lib/OAppAuth/src/",
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
polygon = "${MATIC_RPC_URL}"
bsc = "${BNB_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
base = "${BASE_RPC_URL}"
zircuit = "${ZIRCUIT_RPC_URL}"
scroll = "${SCROLL_RPC_URL}"
linea = "${LINEA_RPC_URL}"
sonicMainnet = "${SONIC_MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
sonicTestnet = "${SONIC_TESTNET_RPC_URL}"
corn = "${CORN_MAIZENET_RPC_URL}"
swell = "${SWELL_CHAIN_RPC_URL}"
bob = "${BOB_RPC_URL}"
berachainTestnet = "${BERA_TESTNET_RPC_URL}"
berachain = "${BERA_CHAIN_RPC_URL}"
bartio = "${BARTIO_RPC_URL}"
holesky = "${HOLESKY_RPC_URL}"
unichain = "${UNICHAIN_RPC_URL}"
flare = "${FLARE_RPC_URL}"
ink = "${INK_RPC_URL}"
plume = "${PLUME_RPC_URL}"

[etherscan]
berachain = { key = "${BERASCAN_KEY}", chain = 80094, url = "https://api.berascan.com/api" }
ink = { key = "${INKSCAN_KEY}", chain = 57073, url = "https://explorer.inkonchain.com/api/" }
plume = { key = "${PLUMESCAN_KEY}", chain = 98866, url = "https://explorer-plume-mainnet-1.t.conduit.xyz/api/" }

[fmt]
FOUNDRY_FMT_LINE_LENGTH = 120
FOUNDRY_FMT_TAB_WIDTH = 4
FOUNDRY_FMT_BRACKET_SPACING = true
FOUNDRY_FMT_INT_TYPES = "long"
FOUNDRY_FMT_MULTILINE_FUNC_HEADER = "attributes_first"
FOUNDRY_FMT_QUOTE_STYLE = "double"
FOUNDRY_FMT_NUMBER_UNDERSCORE = "thousands"
FOUNDRY_FMT_OVERRIDE_SPACING = true
FOUNDRY_FMT_WRAP_COMMENTS = false
FOUNDRY_FMT_IGNORE = []
