# invariants
certora/scripts/setup.sh C

# certoraRun certora/confs/scenarioC.conf --msg exchangeRateLEhighwaterMark_unlessPaused --rule exchangeRateLEhighwaterMark_unlessPaused --verify "TellerWithYieldStreaming:certora/specs/teller_accounting_hardRules.spec" --prover_args "-destructiveOptimizations twostage -mediumTimeout 20 -lowTimeout 20 -tinyTimeout 20 -depth 20 -splitParallel true"
certoraRun certora/confs/scenarioC.conf --msg sharePriceBoundedLower --rule sharePriceBoundedLower --verify "TellerWithYieldStreaming:certora/specs/teller_accounting_hardRules.spec" --prover_args "-destructiveOptimizations twostage -mediumTimeout 20 -lowTimeout 20 -tinyTimeout 20 -depth 20 -splitParallel true"
certoraRun certora/confs/scenarioC.conf --msg exchangeRateEqlastSharePrice --rule exchangeRateEqlastSharePrice --verify "TellerWithYieldStreaming:certora/specs/teller_accounting_hardRules.spec" --prover_args "-destructiveOptimizations twostage -mediumTimeout 20 -lowTimeout 20 -tinyTimeout 20 -depth 20 -splitParallel true"
certoraRun certora/confs/scenarioC.conf --msg cumulativeSupplyBounded --rule cumulativeSupplyBounded --verify "TellerWithYieldStreaming:certora/specs/teller_accounting_hardRules.spec" --prover_args "-destructiveOptimizations twostage -mediumTimeout 20 -lowTimeout 20 -tinyTimeout 20 -depth 20 -splitParallel true"
certoraRun certora/confs/scenarioC.conf --msg sharePriceBoundedUpper --rule sharePriceBoundedUpper --verify "TellerWithYieldStreaming:certora/specs/teller_accounting_hardRules.spec" --prover_args "-destructiveOptimizations twostage -mediumTimeout 20 -lowTimeout 20 -tinyTimeout 20 -depth 20 -splitParallel true"
certoraRun certora/confs/scenarioC.conf --msg sharePriceMoreThanOneAsset --rule sharePriceMoreThanOneAsset --verify "TellerWithYieldStreaming:certora/specs/teller_accounting_hardRules.spec" --prover_args "-destructiveOptimizations twostage -mediumTimeout 20 -lowTimeout 20 -tinyTimeout 20 -depth 20 -splitParallel true"

certoraRun certora/confs/scenarioC.conf --msg assetsMoreThanShares --rule assetsMoreThanShares --verify "TellerWithYieldStreaming:certora/specs/teller_accounting_hardRules.spec" --prover_args "-destructiveOptimizations twostage -mediumTimeout 20 -lowTimeout 20 -tinyTimeout 20 -depth 20 -splitParallel true"
certoraRun certora/confs/scenarioC.conf --msg totalAssetsCovered --rule totalAssetsCovered --verify "TellerWithYieldStreaming:certora/specs/teller_accounting_hardRules.spec" --prover_args "-destructiveOptimizations twostage -mediumTimeout 20 -lowTimeout 20 -tinyTimeout 20 -depth 20 -splitParallel true"
certoraRun certora/confs/scenarioC.conf --msg vaultSolvency_1Asset --rule vaultSolvency_1Asset --verify "TellerWithYieldStreaming:certora/specs/teller_accounting_hardRules.spec" --prover_args "-destructiveOptimizations twostage -mediumTimeout 20 -lowTimeout 20 -tinyTimeout 20 -depth 20 -splitParallel true"


certoraRun certora/confs/scenarioC.conf --msg sharePriceBoundedUpper_strict --rule sharePriceBoundedUpper_strict --verify "TellerWithYieldStreaming:certora/specs/teller_accounting_hardRules.spec" --prover_args "-destructiveOptimizations twostage -mediumTimeout 20 -lowTimeout 20 -tinyTimeout 20 -depth 20 -splitParallel true"
